Webspashpage
davidhu2000/youtube_desktop pull request #36
Opened 2017-04-11 03:32 UTC by asherman-ca

-created webpage for app hosting
-added sections for technologies and features 
-material styles
-buttons
-polish

2017-04-11 06:39 UTC, davidhu2000 requested changes
I made some comments in the code, please review and update the pull request. 

Also, I updated `home_page.png`, so do `git pull` before making changes.

2017-04-11 06:39 UTC, davidhu2000 commented on docs/index.html
> +        Mac Free Download</a>
we can make this button more dynamic, use javascript to detect which Operating System the user is using and adjust this button accordingly. 

We can default to OSX, and when the page loads, the button will change accordingly.

We can write a script at the end of the file 

```
var OSName="Unknown OS";
if (navigator.appVersion.indexOf("Win")!=-1) {
  // make button say windows download
} else if (navigator.appVersion.indexOf("Mac")!=-1){
  // make button say mac download
} else if (navigator.appVersion.indexOf("Linux")!=-1) {
  // make button say linux download
};
```

2017-04-11 06:39 UTC, davidhu2000 commented on docs/index.html
> +    </footer>
The part feels a little cramped, can we expand the footer session? Maybe add a bit of description? 

The footer should just include some contact info, maybe some copyright stuff.

2017-04-11 06:39 UTC, davidhu2000 commented on docs/index.html
> +
we need a section somewhere that includes the download links for all the different platforms, just in case the dynamic button doesn't work properly.

2017-04-11 06:39 UTC, davidhu2000 commented on docs/styles.css
> +}*/
delete this code.

2017-04-11 07:23 UTC, davidhu2000 commented on docs/index.html
> +      <a href="#">
let's make this link to the GitHub repo; so when the landing page is live, people can click the button and go somewhere.

2017-04-14 00:26 UTC, asherman-ca commented
-made all requested changes

2017-04-14 00:45 UTC, davidhu2000 approved these changes

2017-04-14 00:46 UTC, merged